### ISSUE TITLE
Importing spatial mechanism fails

### ISSUE THREAD

**Issue by nyxaria** [kktse/slvstopy#47]
Hi, thanks so much for your amazing work. I've been trying to simulate a spatial mechanism the construction of which is quite complex so this package helps out a lot. However, I am not able to import the mechanism I designed into python due to the following error:

```
Traceback (most recent call last):
  File "/Users/georgehartt/pyss_test.py", line 7, in <module>
    system, entities = slvs_to_py.generate_system()
  File "/Users/georgehartt/slvstopy/src/slvstopy/__init__.py", line 26, in generate_system
    return self._generate_system(self.entity_definition, self.constraint_definition)
  File "/Users/georgehartt/slvstopy/src/slvstopy/__init__.py", line 48, in _generate_system
    constraint_service.construct_constraints(constraint_definition)
  File "/Users/georgehartt/slvstopy/src/slvstopy/services.py", line 213, in construct_constraints
    self.construct_constraint(constraint_definition)
  File "/Users/georgehartt/slvstopy/services.py", line 375, in construct_constraint
    self.constraint_repository.add_parallel(entity_a, entity_b, workplane)
  File "/Users/georgehartt/slvstopy/src/slvstopy/repositories.py", line 333, in add_parallel
    raise NotImplementedError("Workplane cannot be Entity.FREE_IN_3D")
NotImplementedError: Workplane cannot be Entity.FREE_IN_3D
```
[5R.slvs.zip](https://github.com/kktse/slvstopy/files/8732086/5R.slvs.zip)

I have attached the slvs file here, do you mind helping me out? I have an inclination that this is because the python bindings don't support `angle` between 3d lines -- is this true? If so, how do you recommend I analyse complex 3d linkages without going to C? Many thanks!

**Comment by kktse** [comment]
Apologies for the very delayed response. This does appear to be a problem with the bindings with the parallel constraints in 3D. I did a quick test bumping the solvespace-python==3.0.7 to no avail; I had some WIP which added a test specifically with this concern. It may be worthwhile raising an issue upstream, and there is a rather comprehensive test suite in this project that can make it easy to highlight this problem.

The limitation of this library is that the linkage needs to be drawn in a particular way to ensure compatibility. In this instance, the way I'd work around is by fixing the point on the XY plane (25, 16, 0) using a where-dragged constraint. The workflow is a bit odd in that you have to dimension the point, overconstrain it, and then delete the linear dimensions. Hopefully I understood the intent of the linkage correctly. 

I'll try to do a bit more investigating on how this can work out-of-the-box.

**Comment by kktse** [comment]
Updating to solvespace-python==3.0.7

Motivating test:
```python
from python_solvespace import SolverSystem
from slvstopy.repositories import ConstraintRepository, EntityRepository

system = SolverSystem()
constraint_repository = ConstraintRepository(system=system)
entity_repository = EntityRepository(system=system)

origin = entity_repository.create_point_in_3d("99999990", 0.0, 0.0, 0.0)
point_a = entity_repository.create_point_in_3d(
    "99999993", 0.0, 0.0, 0.
)
point_b = entity_repository.create_point_in_3d(
    "99999994", 5.0, 0.0, 0.
)
point_c = entity_repository.create_point_in_3d(
    "99999995", 0.0, 5.0, 0. 
)
point_d = entity_repository.create_point_in_3d(
    "99999996", 5.0, 10.0, 0. 
)
line_a = entity_repository.create_line_segment(
    "99999997", point_a, point_b
)
line_b = entity_repository.create_line_segment(
    "99999998", point_c, point_d
)
constraint_repository.add_where_dragged(point_a)
constraint_repository.add_where_dragged(point_b)
constraint_repository.add_parallel(line_a, line_b)

result = system.solve()
```

Error message
```
$ python test.py
File python_solvespace/src/constrainteq.cpp, line 223, function ModifyToSatisfy:
Assertion failed: l.n == 1.
Message: Expected constraint to generate a single equation.
[1]    133946 IOT instruction (core dumped)  python test.py

```

**Comment by kktse** [comment]
I am open to submissions to this issue, either to identify a workaround or resolve upstream.

I can make the Parallel in 3d constraint available, but can not guarantee that it would work.

In the meantime, I must note this library is not a one-to-one implementation of the Solvespace GUI. The way I have worked around this is by avoiding problematic constraints such as this one. This therefore requires linkages to be drawn with this library in mind. This is rather frustrating, but hopefully I can get help identifying what is happening at the solver here.

**Comment by nyxaria** [comment]
Thank you so much for your reply, I have been ill for the past year so have not had the chance to reply to you. But I really appreciate your help in this. I just started looking at this again and solved it as your suggested by using two perpendicular constraints to replace a parallel constraint.
